### ISSUE TITLE
Is Code publicly available?

### ISSUE THREAD

**Issue by hadifar** [HaniehP/PersianNER#1]
Hi, thanks for your great dataset.
Is paper's code publicly available?

**Comment by hadifar** [comment]
I find an implementation: [here](https://github.com/AminMozhgani/Persian_NER) :)

**Comment by HaniehP** [comment]
I used [NeuroNer ](https://github.com/Franck-Dernoncourt/NeuroNER)for training the BiLSTM-CRF model.
